all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: ubuntu
    prod:
      vars:
        env: prod
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

      hosts:
        odoo_host:
          ansible_host: 172.31.86.185
          hostname: TBD
